# Generated by Django 3.0.6 on 2020-06-04 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 6, 4, 21, 37, 49, 343961, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
